name: Build and Test .NET Framework

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: mono-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ matrix.nuget }}
    - run: nuget restore Web-Series-API--ASP.NET.sln
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore Web-Series-API--ASP.NET.sln

    - name: Build Solution
      run: |
        msbuild.exe Web-Series-API--ASP.NET.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
