name: Build and Test .NET Framework

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.8.x'

    - name: Build and Test
      run: |
        dotnet restore
        dotnet build
        dotnet test
